module.exports = {
  APP_PORT: 3333,
  DEFAULT_SEARCH_LEVEL: 2,
  REDIS_HOST: '127.0.0.1',
  REDIS_PORT: 6379,
  REDIS_SESSION_EXPIRE: 60 * 60 * 24,
  ACCEPTABLE_CONTENT_TYPES: ['text/html', 'text/plain'],
  ACCEPTABLE_STATUS_CODE: 200,
  ACCEPTABLE_STATUS_MESSAGE: 'OK',
};
